version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      - ENV_VARIABLE=value1
      - NEXT_PUBLIC_ENV_VARIABLE=value2
    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./frontend:/frontend
    restart: always
    ports:
      - 3000:3000
    networks:
      - apprenticeshipreporter

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "nado"
      # You can use whatever password you like
      MYSQL_PASSWORD: "lol"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

# Names our volume
volumes:
  my-db:

networks:
  apprenticeshipreporter:
    external: true
