version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      target: runner
    volumes:
      - .:./frontend/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
