version: "3"

services:
  nextjs:
    container_name: frontend
    hostname: nextjs
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - net

  maven:
    depends_on:
      - db
    container_name: backend
    hostname: maven
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - 8080:8080
      # - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    networks:
      - net

  db:
    container_name: mysql
    hostname: mysqldb
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_DATABASE: apprenticeshipreporter
      MYSQL_USER: nado
      MYSQL_PASSWORD: lol
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - net

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  my-db:

networks:
  net:
