version: "3"

services:
  nextjs:
    container_name: frontend
    hostname: nextjs
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    env_file:
      - stack.env
    restart: always
    ports:
      - 3000:3000

    networks:
      - net

  maven:
    depends_on:
      - db
    container_name: backend
    hostname: maven
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
    restart: always
    env_file:
      - stack.env
    ports:
      - 8080:8080
      # - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQLDB_DOCKER_PORT: ${MYSQLDB_DOCKER_PORT}
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/apprenticeshipreporter?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username": "${MYSQL_USER}",
        "spring.datasource.password": "${MYSQL_PASSWORD}",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
        }'

    networks:
      - net

  db:
    container_name: mysql
    hostname: mysqldb
    image: mysql:8.0.33
    restart: always
    env_file:
      - stack.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQLDB_DOCKER_PORT: ${MYSQLDB_DOCKER_PORT}
    ports:
      - "${MYSQLDB_DOCKER_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - my-db:/var/lib/mysql

    networks:
      - net

volumes:
  my-db:

networks:
  net:
