version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      - ENV_VARIABLE=value1
      - NEXT_PUBLIC_ENV_VARIABLE=value2
    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./frontend:/frontend
    restart: always
    ports:
      - 3000:3000
    networks:
      - apprenticeshipreporter

# Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  apprenticeshipreporter:
    external: true
