# Use an official Node.js runtime as a parent image
FROM node:16-alpine

# Set the working directory in the container
WORKDIR /

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of your frontend application code to the container
COPY . .

# Build the frontend application
RUN npm run build

# Expose the port your frontend application will run on
EXPOSE 3000

# Command to start your application
CMD ["npm", "start"]
